# Host to use for canonical URL generation (without trailing slash)
host: https://www.identity-providers.verify.service.gov.uk

# GOV.UK logo set to false until deployed to .service.gov.uk domain
show_govuk_logo: true

# Header-related options
service_name: Verify
service_link: https://www.verify.service.gov.uk
## phase of your project, for example ALPHA, BETA
# phase: TESTING PHASE

# Links to show on right-hand-side of header
header_links:
  About: https://www.verify.service.gov.uk
# Connect: https://www.verify.service.gov.uk/connect # Does not apply to IDPs
# Documentation: https://www.docs.verify.service.gov.uk # Does not apply to IDPs
  Support: https://www.verify.service.gov.uk/support

# Links to show in the page footer
footer_links:
  Accessibility: /accessibility-statement

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Setting show_expiry: false to not have a red banner when it's past the review due date. The review_in parameter in the frontmatter is for internal use.
show_expiry: false

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 3

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: alphagov/verify-idp-guidance
